import enum
from uuid import uuid4

from pgvector.sqlalchemy import Vector
from sqlalchemy import (
    BigInteger,
    Boolean,
    CheckConstraint,
    Column,
    DateTime,
    Enum,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    UniqueConstraint,
    func,
    text,
)
from sqlalchemy.dialects.postgresql import ARRAY, UUID
from sqlalchemy.orm import relationship

from .database import Base


class SubscriptionPlan(enum.Enum):
    trial = "trial"
    basic = "basic"
    pro = "pro"


class SubscriptionStatus(enum.Enum):
    active = "active"
    expired = "expired"
    cancelled = "cancelled"


class User(Base):
    """Registered user account. Auth is handled via linked UserIdentity records."""

    __tablename__ = "users"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid4)
    first_name = Column(String(50), nullable=False)
    last_name = Column(String(50), nullable=False)
    year_of_birth = Column(Integer, nullable=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now())

    # A user can have multiple auth methods (email, phone, Google)
    identities = relationship(
        "UserIdentity", back_populates="user", cascade="all, delete-orphan"
    )
    subscription = relationship(
        "UserSubscription", back_populates="user", uselist=False, cascade="all, delete-orphan"
    )

    __table_args__ = (
        CheckConstraint("year_of_birth > 1900", name="ck_users_year_of_birth"),
    )


class UserIdentity(Base):
    """Links a user to an external auth provider (email OTP, phone OTP, Google OAuth).

    provider_id is the provider-specific unique identifier:
      - email/phone: the address/number itself
      - google: the Google sub claim
    """

    __tablename__ = "user_identities"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid4)
    user_id = Column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )
    provider = Column(String(20), nullable=False)  # 'email', 'phone', 'google'
    provider_id = Column(String(255), nullable=False)
    is_verified = Column(Boolean, default=False)

    user = relationship("User", back_populates="identities")

    __table_args__ = (
        # Each (provider, provider_id) pair must be globally unique
        UniqueConstraint("provider", "provider_id", name="uq_identity_provider_id"),
    )


class UserSubscription(Base):
    """Tracks a user's subscription plan and free trial window.

    Every new user gets a 7-day trial automatically.
    Trial validity: trial_start ≤ now < trial_end (both UTC).
    """

    __tablename__ = "user_subscriptions"

    id = Column(Integer, primary_key=True, autoincrement=True)
    user_id = Column(
        UUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        unique=True,
    )
    plan = Column(
        Enum(SubscriptionPlan), nullable=False, default=SubscriptionPlan.trial
    )
    status = Column(
        Enum(SubscriptionStatus), nullable=False, default=SubscriptionStatus.active
    )
    trial_start = Column(DateTime(timezone=True), nullable=True)
    trial_end = Column(DateTime(timezone=True), nullable=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)

    user = relationship("User", back_populates="subscription")


class OTPCode(Base):
    """Stores a pending OTP challenge for email/phone login.

    The OTP value itself is hashed; the plaintext is never stored.
    Expired or used codes should be purged periodically.
    """

    __tablename__ = "otp_codes"

    id = Column(Integer, primary_key=True, autoincrement=True)
    # Email address or phone number the OTP was sent to
    identifier = Column(String(255), index=True, nullable=False)
    otp_hash = Column(String(255), nullable=False)
    expires_at = Column(DateTime(timezone=True), nullable=False)
    # Tracks failed verification attempts to support rate-limiting / lockout
    attempts = Column(Integer, default=0)


class Document(Base):
    """A single GST judgment. Metadata is sourced from the parquet files produced
    by the sharding pipeline; content is the HTML generated by the ETL transform step.

    case_id is the canonical dedup key — upserting a document deletes the old record
    and all its chunks before inserting the new one.
    """

    __tablename__ = "documents"

    id = Column(Integer, primary_key=True, index=True)
    title = Column(Text, nullable=False)
    petitioner = Column(Text, nullable=False)
    respondent = Column(Text, nullable=False)
    judge = Column(Text, nullable=False)
    citation = Column(Text, nullable=False)
    decision_date = Column(Text, nullable=False)
    disposal_nature = Column(Text, nullable=True)
    court = Column(Text, nullable=False)
    # Stable identifier from source data (e.g. CNR number); unique across all docs
    case_id = Column(Text, nullable=False, unique=True)
    # Raw text used for full-text or fallback search
    content = Column(Text, nullable=False)
    # HTML rendered for the document detail page (may be None for legacy records)
    display_content = Column(Text, nullable=True)

    # ML-extracted fields from filter step
    is_gst_core = Column(Boolean, nullable=True, default=None)
    extracted_provisions: Column = Column(ARRAY(Text), nullable=True)
    extracted_statutes: Column = Column(ARRAY(Text), nullable=True)

    # (Section, Act) pairs extracted from analysis JSONs — "Section 16|CGST Act"
    # Populated by etl/extract_act_sections.py
    act_sections: Column = Column(ARRAY(Text), nullable=True)
    # Convenience: just the provision strings without act suffix (legacy extract_provisions.py)
    primary_provisions: Column = Column(ARRAY(Text), nullable=True)

    # Timestamps for sync support
    created_at = Column(
        DateTime(timezone=True), server_default=func.now(), nullable=False
    )
    updated_at = Column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )

    chunks = relationship("DocumentChunk", back_populates="document")


class DocumentChunk(Base):
    """A text chunk of a Document with its vector embedding.

    Documents are split into chunks of ~4000 chars (600 char overlap) by the ETL
    transform step. Each chunk stores a 384-dim embedding produced by
    all-MiniLM-L6-v2, used for cosine-distance similarity search via pgvector.
    """

    __tablename__ = "document_chunks"
    __table_args__ = (
        Index(
            "idx_chunks_fts",
            text("to_tsvector('english', chunk_content)"),
            postgresql_using="gin",
        ),
    )

    id = Column(Integer, primary_key=True, index=True)
    document_id = Column(Integer, ForeignKey("documents.id"), nullable=False)
    chunk_content = Column(Text, nullable=False)
    # 384-dimensional embedding vector (all-MiniLM-L6-v2)
    embedding = Column(Vector(768))
    document = relationship("Document", back_populates="chunks")


# ─────────────────────────────────────────────────────────────────────────────
# Legal Reference Library
# Four document types (Acts, Rules, Notifications, Circulars) plus a
# cross_references table that captures hyperlinks parsed from html_content.
# ─────────────────────────────────────────────────────────────────────────────


class DocType(enum.Enum):
    """Discriminator enum shared by CrossReference source/target columns."""

    act = "act"
    rule = "rule"
    notification = "notification"
    circular = "circular"


class Act(Base):
    """One section of a GST act (CGST, IGST, UTGST, Compensation, Constitution Amendment).

    Each JSON item in .data/acts/ maps to one row.
    primary_id comes from the source system and is the value embedded in
    cross-reference URLs (explore-act/{primary_id}).
    """

    __tablename__ = "acts"

    id = Column(Integer, primary_key=True, autoincrement=True)
    primary_id = Column(Integer, nullable=False)
    content_id = Column(BigInteger, nullable=False, unique=True)  # prefix 1111x
    act_name = Column(Text, nullable=False)       # "CGST Act", "IGST Act", …
    chapter_no = Column(Text, nullable=True)      # "Chapter I"
    chapter_name = Column(Text, nullable=True)    # "Preliminary"
    section_no = Column(Text, nullable=False)     # "Section 1"
    section_name = Column(Text, nullable=True)
    content = Column(Text, nullable=True)         # plain text for FTS / search
    html_content = Column(Text, nullable=True)    # raw HTML for rendering
    source_url = Column(Text, nullable=True)
    # Gemini-generated annotations for semantic search enrichment
    q1 = Column(Text, nullable=True)       # practitioner question 1
    q2 = Column(Text, nullable=True)       # practitioner question 2
    q3 = Column(Text, nullable=True)       # practitioner question 3
    ann_summary = Column(Text, nullable=True)  # one-sentence plain-English summary
    # 384-dim semantic embedding (all-MiniLM-L6-v2); nullable so rows can be
    # inserted before the embedding step runs.
    embedding = Column(Vector(768), nullable=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    updated_at = Column(DateTime(timezone=True), server_default=func.now(),
                        onupdate=func.now(), nullable=False)

    cross_references_out = relationship(
        "CrossReference",
        primaryjoin="and_(CrossReference.source_type=='act', "
                    "foreign(CrossReference.source_id)==Act.primary_id)",
        viewonly=True,
    )

    __table_args__ = (
        Index("idx_acts_primary_id", "primary_id"),
        Index("idx_acts_act_name", "act_name"),
        Index("idx_acts_chapter", "act_name", "chapter_no"),
        Index(
            "idx_acts_fts",
            text("to_tsvector('english', coalesce(content, ''))"),
            postgresql_using="gin",
        ),
        Index(
            "idx_acts_embedding_hnsw",
            "embedding",
            postgresql_using="hnsw",
            postgresql_with={"m": 16, "ef_construction": 64},
            postgresql_ops={"embedding": "vector_cosine_ops"},
        ),
    )


class ActChunk(Base):
    """A sub-section chunk of an Act section with its vector embedding.

    Each Act row is split at top-level numbered sub-section boundaries
    (e.g. (1), (2), (5)) so that searches hit the precise sub-section
    rather than the entire section blob.
    """

    __tablename__ = "act_chunks"
    __table_args__ = (
        Index(
            "idx_act_chunks_fts",
            text("to_tsvector('english', chunk_content)"),
            postgresql_using="gin",
        ),
        Index(
            "idx_act_chunks_embedding_hnsw",
            "embedding",
            postgresql_using="hnsw",
            postgresql_with={"m": 16, "ef_construction": 64},
            postgresql_ops={"embedding": "vector_cosine_ops"},
        ),
    )

    id = Column(Integer, primary_key=True, autoincrement=True)
    act_id = Column(Integer, ForeignKey("acts.id", ondelete="CASCADE"), nullable=False)
    # e.g. "Section 17(5)" or "Section 17" for the preamble
    sub_section_label = Column(Text, nullable=False)
    chunk_content = Column(Text, nullable=False)
    # LLM-augmented text: plain-English questions + summary prepended to chunk_content.
    # When present, this is what gets embedded instead of raw chunk_content.
    # Populated by etl/augment_acts.py (one-time Claude Batch API pass).
    embedding_text = Column(Text, nullable=True)
    # 768-dim embedding (all-mpnet-base-v2) — larger model than case law chunks
    embedding = Column(Vector(768), nullable=True)

    act = relationship("Act", backref="chunks")


class Rule(Base):
    """One rule (or sub-rule) from CGST/IGST Rules.

    Each JSON item in .data/rules/ maps to one row.
    """

    __tablename__ = "rules"

    id = Column(Integer, primary_key=True, autoincrement=True)
    primary_id = Column(Integer, nullable=False)
    content_id = Column(BigInteger, nullable=False, unique=True)  # prefix 122x
    act_name = Column(Text, nullable=False)       # "CGST Rules", "IGST Rules"
    chapter_id = Column(Integer, nullable=True)   # raw chapter reference from source
    section_no = Column(Text, nullable=False)     # "Rule 1", "Introduction"
    section_name = Column(Text, nullable=True)
    content = Column(Text, nullable=True)
    html_content = Column(Text, nullable=True)
    source_url = Column(Text, nullable=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    updated_at = Column(DateTime(timezone=True), server_default=func.now(),
                        onupdate=func.now(), nullable=False)

    q1 = Column(Text, nullable=True)
    q2 = Column(Text, nullable=True)
    q3 = Column(Text, nullable=True)
    ann_summary = Column(Text, nullable=True)

    cross_references_out = relationship(
        "CrossReference",
        primaryjoin="and_(CrossReference.source_type=='rule', "
                    "foreign(CrossReference.source_id)==Rule.primary_id)",
        viewonly=True,
    )

    __table_args__ = (
        Index("idx_rules_primary_id", "primary_id"),
        Index("idx_rules_act_name", "act_name"),
        Index(
            "idx_rules_fts",
            text("to_tsvector('english', coalesce(content, ''))"),
            postgresql_using="gin",
        ),
    )


class RuleChunk(Base):
    """A sub-section chunk of a Rule section with its vector embedding."""

    __tablename__ = "rule_chunks"
    __table_args__ = (
        Index(
            "idx_rule_chunks_fts",
            text("to_tsvector('english', chunk_content)"),
            postgresql_using="gin",
        ),
        Index(
            "idx_rule_chunks_embedding_hnsw",
            "embedding",
            postgresql_using="hnsw",
            postgresql_with={"m": 16, "ef_construction": 64},
            postgresql_ops={"embedding": "vector_cosine_ops"},
        ),
    )

    id = Column(Integer, primary_key=True, autoincrement=True)
    rule_id = Column(Integer, ForeignKey("rules.id", ondelete="CASCADE"), nullable=False)
    sub_section_label = Column(Text, nullable=False)
    chunk_content = Column(Text, nullable=False)
    embedding_text = Column(Text, nullable=True)
    embedding = Column(Vector(768), nullable=True)

    rule = relationship("Rule", backref="chunks")


class Notification(Base):
    """A GST notification (Central Tax, Integrated Tax, Compensation Cess, etc.).

    Each JSON item in .data/notifications/jsons/ maps to one row.
    meta fields (category, year, doc_path, order_id) are flattened into columns
    for efficient filtering rather than stored as JSONB.
    """

    __tablename__ = "notifications"

    id = Column(Integer, primary_key=True, autoincrement=True)
    primary_id = Column(Integer, nullable=False, unique=True)  # used in cross-ref URLs
    content_id = Column(BigInteger, nullable=False, unique=True)  # prefix 150x
    notification_no = Column(Text, nullable=False)   # "75/2017-Central Tax"
    issued_on = Column(DateTime(timezone=True), nullable=True)
    title = Column(Text, nullable=True)
    content = Column(Text, nullable=True)
    category = Column(Text, nullable=True)           # "Central Tax", "Central Tax Rate", …
    year = Column(Integer, nullable=True)
    doc_path = Column(Text, nullable=True)
    order_id = Column(BigInteger, nullable=True)
    is_active = Column(Boolean, nullable=False, default=True)
    is_amended = Column(Boolean, nullable=False, default=False)
    structured_html = Column(Text, nullable=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    updated_at = Column(DateTime(timezone=True), server_default=func.now(),
                        onupdate=func.now(), nullable=False)

    __table_args__ = (
        Index("idx_notifications_category", "category"),
        Index("idx_notifications_year", "year"),
        Index(
            "idx_notifications_fts",
            text("to_tsvector('english', coalesce(title, '') || ' ' || coalesce(content, ''))"),
            postgresql_using="gin",
        ),
    )


class Circular(Base):
    """A GST circular (CGST, IGST, CESS).

    Each JSON item in .data/circulars/jsons/ maps to one row.
    primary_id is an integer (source system), consistent with other types.
    circular_no is the human-readable identifier e.g. "1/1/2017".
    """

    __tablename__ = "circulars"

    id = Column(Integer, primary_key=True, autoincrement=True)
    primary_id = Column(Integer, nullable=False, unique=True)  # used in cross-ref URLs
    content_id = Column(BigInteger, nullable=False, unique=True)  # prefix 160x
    circular_no = Column(Text, nullable=False)       # "1/1/2017"
    issued_on = Column(DateTime(timezone=True), nullable=True)
    subject = Column(Text, nullable=True)
    content = Column(Text, nullable=True)
    category = Column(Text, nullable=True)           # "CGST", "IGST", "CESS"
    year = Column(Integer, nullable=True)
    doc_path = Column(Text, nullable=True)
    order_id = Column(BigInteger, nullable=True)
    is_active = Column(Boolean, nullable=False, default=True)
    is_amended = Column(Boolean, nullable=False, default=False)
    structured_html = Column(Text, nullable=True)
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    updated_at = Column(DateTime(timezone=True), server_default=func.now(),
                        onupdate=func.now(), nullable=False)

    __table_args__ = (
        Index("idx_circulars_primary_id", "primary_id"),
        Index("idx_circulars_category", "category"),
        Index("idx_circulars_year", "year"),
        Index(
            "idx_circulars_fts",
            text("to_tsvector('english', coalesce(subject, '') || ' ' || coalesce(content, ''))"),
            postgresql_using="gin",
        ),
    )


class LibraryChunk(Base):
    """A text chunk of a Notification or Circular with its vector embedding.

    Populated by etl/embed_library_docs.py. Used for hybrid FTS + semantic
    search over notifications and circulars separately.
    """

    __tablename__ = "library_chunks"

    id = Column(Integer, primary_key=True, autoincrement=True)
    doc_type = Column(Text, nullable=False)       # 'notification' or 'circular'
    primary_id = Column(Integer, nullable=False)
    chunk_index = Column(Integer, nullable=False)
    content = Column(Text, nullable=False)
    embedding_text = Column(Text, nullable=True)  # LLM-generated prefix (questions + summary)
    embedding = Column(Vector(768), nullable=True)

    __table_args__ = (
        UniqueConstraint("doc_type", "primary_id", "chunk_index", name="uq_library_chunk"),
        Index("idx_library_chunks_lookup", "doc_type", "primary_id"),
        Index(
            "idx_library_chunks_fts",
            text("to_tsvector('english', content)"),
            postgresql_using="gin",
        ),
        Index(
            "idx_library_chunks_embedding",
            "embedding",
            postgresql_using="ivfflat",
            postgresql_ops={"embedding": "vector_cosine_ops"},
            postgresql_with={"lists": 100},
        ),
    )


class CrossReference(Base):
    """A hyperlink parsed from html_content of an Act or Rule pointing to another document.

    source_type / source_id  — the Act or Rule section the link appears in.
    target_type / target_id  — the document the link points to (primary_id of that table).

    Links follow the pattern: explore-{target_type}/{target_id}
    Populated entirely by the ingestion pipeline; never written by the API.
    """

    __tablename__ = "cross_references"

    id = Column(Integer, primary_key=True, autoincrement=True)
    source_type = Column(Enum(DocType), nullable=False)
    source_id = Column(Integer, nullable=False)    # primary_id of the source Act/Rule
    target_type = Column(Enum(DocType), nullable=False)
    target_id = Column(Integer, nullable=False)    # primary_id of the target document
    anchor_text = Column(Text, nullable=True)      # visible link text
    created_at = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)

    __table_args__ = (
        UniqueConstraint(
            "source_type", "source_id", "target_type", "target_id",
            name="uq_cross_reference",
        ),
        Index("idx_xref_source", "source_type", "source_id"),
        Index("idx_xref_target", "target_type", "target_id"),
    )


class XrefRelationship(enum.Enum):
    """Validity relationship between two library documents (notifications/circulars)."""
    WITHDRAWS  = "WITHDRAWS"   # from_doc completely withdraws / rescinds to_doc
    SUPERSEDES = "SUPERSEDES"  # from_doc replaces to_doc (to_doc is no longer operative)
    AMENDS     = "AMENDS"      # from_doc partially modifies to_doc (to_doc still valid)


class LibraryXref(Base):
    """Validity relationships between notifications and circulars.

    from_doc (the newer document) has relationship WITHDRAWS/SUPERSEDES/AMENDS to_doc.
    When relationship is WITHDRAWS or SUPERSEDES, to_doc.is_active should be False.
    Populated by etl/build_xrefs.py; never written by the API.
    """

    __tablename__ = "library_xrefs"

    id             = Column(Integer, primary_key=True, autoincrement=True)
    from_doc_type  = Column(Enum(DocType), nullable=False)
    from_primary_id = Column(Integer, nullable=False)
    to_doc_type    = Column(Enum(DocType), nullable=False)
    to_primary_id  = Column(Integer, nullable=False)
    relationship   = Column(Enum(XrefRelationship), nullable=False)
    ab_initio      = Column(Boolean, nullable=False, default=False)  # withdrawn as if never issued
    created_at     = Column(DateTime(timezone=True), server_default=func.now(), nullable=False)

    __table_args__ = (
        UniqueConstraint(
            "from_doc_type", "from_primary_id", "to_doc_type", "to_primary_id",
            name="uq_library_xref",
        ),
        Index("idx_lxref_from", "from_doc_type", "from_primary_id"),
        Index("idx_lxref_to",   "to_doc_type",   "to_primary_id"),
    )
