[project]
name = "legalsearchetl"
version = "0.1.0"
description = "ETL service for LegalSearch"
requires-python = ">=3.13"
dependencies = [
    "sqlalchemy",
    "psycopg2-binary",
    "transformers",
    "torch",
    "beautifulsoup4",
    "pymupdf", 
    "python-dotenv",
]

[tool.hatch.build.targets.wheel]
packages = ["."]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
